### ISSUE TITLE
Extract (and display) flux per pathway segment

### ISSUE THREAD

**Issue by gkiss** [brycecr/msmexplorer#53]
Hey Bryce,
I'm trying to label the pathways with the flux between states.
What is the best way to extract these values from the TPT calculation in MSMExplorer?
Thanks,
Gert

**Comment by brycecr** [comment]
Hey Gert,

Thanks for the issue! Those are good feature requests...

It really seems like those flux values should be saveable, so I just added two menu items under the Panels menu "Save Node Table" and "Save Edge Table", which will save the corresponding tables in .csv files. Pretty scrappy, but it at least gets the data into a format that excel can handle. If you pull or download from my repo, you'll get the version with these new menu items. After you run TPT, go back to graph view; at this point Panels->Save Edge Table will save a CSV with the flux column you want.

MSMExplorer doesn't have a way to put labels on edges currently...sorry! I would recommend making the TPT diagram in MSMExplorer, saving the image, and then adding the labels on top in another program. Relative to an easy implementation I could do in MSMExplorer, this will give you more control over which edges have labels, and how the labels are positioned/sized etc. I think this is on the issue list as something to add, though.

Hope that helps a bit. Thanks for the message & patience with MSMExplorer.

Cheers
Bryce

**Comment by gkiss** [comment]
Great! Works like a charm.
Thanks!
