### ISSUE TITLE
TPT Output

### ISSUE THREAD

**Issue by cxhernandez** [brycecr/msmexplorer#54]
Is there anyway to export TPTs to a text file or do batch analyses from the command line?

**Comment by brycecr** [comment]
Hi Carlos,

Thanks for the issue! 

What kind of text file output are you looking for?

MSMExplorer can output the backing data table generated by TPT. After you run TPT and select the number of top paths you want to display, go to Panels->Save Edge Table, and you'll get a table mapping edge (source,dest) pairs to flux in the TPT graph you generated. Note that you need to download the most recent version from my (this) repo to export the edge table.

See Issue #53 for more information. 

No command line TPT operation at the moment, I'm afraid.

Hope that helps!

**Comment by cxhernandez** [comment]
Thanks for your response, Bryce! 

Sorry, I was running the program on "Just TPT" mode and didn't see the Panels menus. The CSV output is very helpful, but I was wondering if it was possible to save data more relevant to the directed TPT graph. 

For example, it would be nice to export a list of the top paths, so if I chose to export the top N paths I'd get a list of N arrays, similar to what is already implemented in msmbuilder:

```
      [[S1,  S2,  S5,   -1.,   -1.,   -1.],
       [ S7,  S6,  S5,   -1.,   -1.,   -1.],
       ...
       [ S1,  S2,  S3,  S4,  S5,   -1.]]
```

Exporting the bottleneck fluxes for these paths might also be useful. Of course, all of this can be parsed and calculated from the CSV with minimal effort, but it would be a nice, convenient feature to have since TPT already calculates this for you.

Thanks!
Carlos

**Comment by brycecr** [comment]
Yep, that's a very sensible request! I'll see what I can do.
