### ISSUE TITLE
problem with the curved edges curving the wrong way

### ISSUE THREAD

**Issue by schwancr** [brycecr/msmexplorer#55]
For some reason the edges are curving in a wacky way. It actually looks like they always have to pass through some imaginary point in space (not corresponding to a node), since all of the edges initially move toward a single point and then to the corresponding node.

![bad_edges](https://f.cloud.github.com/assets/2244902/1477486/1e033b6c-465c-11e3-93ad-240bd70ce221.png)

**Comment by brycecr** [comment]
ug, sorry about that! Should be fixed now...?

**Comment by schwancr** [comment]
Yep, looks good!
